name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${group}.notyourhorse.NotYourHorse
version: ${version}
api-version: 1.13

commands:
  notyourhorse:
    description: Main command for the plugin
    aliases:
      - nyh
      - horse
    permission: notyourhorse.command

permissions:
  notyourhorse.command:
    description: Allows the player to use /notyourhorse
  notyourhorse.bypass:
    description: Allows the player to bypass the plugin
